### ISSUE TITLE
Consider to split the sprint team in two

### ISSUE THREAD

**Issue by mortenwh** [metno/S-ENDA-project-plan#103]
- one group to work on the metadata management
- one group to work on APIs and front end representation of the catalog, etc. (including collaboration with NRK)

**Comment by mortenwh** [comment]
@havardf @geira @mareilew @TAlonglong @aheimsbakk @ferrighi @mpejcoch @epifanio 

Any opinions?

**Comment by geira** [comment]
I suggested something similar, but not entirely:

- one group to work on the metadata management for datasets
- one group to work on APIs, including metadata for services, but also on stuff concerning NRK (developer portal was mentioned, we need to do this anyway)

As far as front end representation of the catalog, we need to discuss whether a common solution is viable. For APIs the natural method is to serve their own metadata when harvested, not tell users to go somewhere else to read them.

**Comment by mortenwh** [comment]
This sounds good - seems you have thought more in detail on this than myself. Let's wait for some more input before we decide next week!
