### ISSUE TITLE
api.met.no supports DCAT-AP-NO

### ISSUE THREAD

**Issue by havardf** [metno/S-ENDA-project-plan#136]

**Comment by mortenwh** [comment]
Can you explain this in relation to what we did in the first sprint? I thought S-ENDA would expose metadata to geonorge which serves DCAT? It makes sense to also support DCAT locally, but how will that be integrated in the architecture? This needs to be clarified.

**Comment by havardf** [comment]
Api supports a flavor of DCAT now. Any further progress has to be done i cooperation with geonorge.no.

Closing this issue,
